export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    "Foggy forest at night, watercolor style, mysterious mood.",
    "Majestic waterfall, photorealistic style, awe-inspiring mood.",
    "Rocky beach at sunrise, impressionist style, peaceful mood.",
    "Snowy mountains in the distance, minimalist style, serene mood.",
    "Sunflower field in the summer, oil painting style, happy mood.",
    "Desert landscape at sunset, abstract style, contemplative mood.",
    "Autumn leaves falling from trees, pointillism style, nostalgic mood.",
    "Underwater coral reef, surreal style, dreamy mood.",
    "Thunderstorm over the city, expressionist style, dramatic mood.",
    "Rainbow over a meadow, pop art style, joyful mood.",
    "Playful kitten with a ball of yarn, cartoon style, whimsical mood.",
    "Majestic lion in the savannah, realistic style, powerful mood.",
    "Elegant horse galloping in a field, sketch style, free-spirited mood.",
    "Cute bunny eating a carrot, pastel style, innocent mood.",
    "Mischievous raccoon stealing food, watercolor style, playful mood.",
    "Majestic eagle soaring in the sky, oil painting style, awe-inspiring mood.",
    "Sassy flamingo posing, neon style, confident mood.",
    "Ferocious shark in the ocean, minimalist style, intense mood.",
    "Regal peacock showing off its feathers, photorealistic style, proud mood.",
    "Adorable otter holding hands, abstract style, loving mood.",
    "Delicious pizza with all the toppings, realistic style, savory mood.",
    "Mouth-watering sushi rolls, watercolor style, fresh mood.",
    "Tasty cupcake with frosting, sketch style, sweet mood.",
    "Juicy hamburger with fries, pop art style, indulgent mood.",
    "Refreshing fruit smoothie, pastel style, healthy mood.",
    "Spicy bowl of noodles, abstract style, bold mood.",
    "Icy margarita in a tropical setting, neon style, relaxed mood.",
    "Crispy fried chicken, photorealistic style, satisfying mood.",
    "Rich cup of coffee, minimalist style, energized mood.",
    "Sweet bowl of ice cream with sprinkles, oil painting style, happy mood.",
    "Energetic kids playing in the park, cartoon style, playful mood.",
    "Romantic couple dancing under the stars, watercolor style, dreamy mood.",
    "Confident businesswoman in a cityscape, realistic style, powerful mood.",
    "Enthusiastic athlete running on a beach, sketch style, free-spirited mood.",
    "Joyful family having a picnic, pastel style, happy mood.",
    "Serious musician playing an instrument, abstract style, introspective mood.",
    "Fashionable model on a runway, neon style, confident mood.",
    "Wise elderly person in a cozy home, photorealistic style, wise mood.",
    "Excited traveler exploring a new city, minimalist style, adventurous mood.",
    "Creative artist in a studio, oil painting style, inspired mood.",
    "Swirling vortex of colors, digital art style, chaotic mood.",
    "Geometric shapes in a monochrome palette, minimalist style, futuristic mood.",
    "Distorted reflection of a city skyline, impressionist style, surreal mood.",
    "Fluid brushstrokes in a neon palette, expressionist style, energetic mood.",
    "Mosaic of patterns and textures, abstract style, intricate mood.",
    "Kaleidoscope of shapes and colors, pop art style, playful mood.",
    "Layers of shapes and lines, sketch style, introspective mood.",
    "Gradient of colors fading into each other, pastel style, peaceful mood.",
    "Collage of different images and textures, mixed media style, eclectic mood.",
    "Doodles and scribbles in a notebook, marker style, whimsical mood.",
    "Enchanted castle in the clouds, digital art style, magical mood.",
    "Mythical dragon in a mystical forest, oil painting style, awe-inspiring mood.",
    "Whimsical unicorn in a candy-colored landscape, cartoon style, playful mood.",
    "Dark wizard casting a spell, photorealistic style, ominous mood.",
    "Mermaid lounging on a rock in the ocean, watercolor style, serene mood.",
    "Cyborg warrior battling futuristic monsters, concept art style, intense mood.",
    "Elaborate fairy tale book cover, mixed media style, enchanting mood.",
    "Steampunk airship soaring through the sky, sketch style, adventurous mood.",
    "Gothic vampire in a Victorian mansion, realistic style, eerie mood.",
    "Futuristic cityscape with neon lights, cyberpunk style, dystopian mood.",
    "Spacecraft landing on an alien planet, digital art style, otherworldly mood.",
    "Futuristic city skyline at night, neon style, cybernetic mood.",
    "Futuristic soldier in a hi-tech suit, concept art style, intense mood.",
    "Time machine in a laboratory, photorealistic style, scientific mood.",
    "Dystopian wasteland with ruined buildings, abstract style, bleak mood.",
    "Cybernetic implants in a human body, mixed media style, futuristic mood.",
    "Androids in a futuristic society, sketch style, philosophical mood.",
    "Extraterrestrial life form in a sci-fi landscape, oil painting style, surreal mood.",
    "Advanced technology in a city of the future, minimalist style, inspiring mood.",
    "Cosmic explosion in outer space, watercolor style, epic mood.",
    "Bustling city street at night, realistic style, vibrant mood.",
    "Graffiti-covered alleyway, impressionist style, gritty mood.",
    "Retro diner with neon lights, pop art style, nostalgic mood.",
    "Busy urban intersection during rush hour, photorealistic style, chaotic mood.",
    "Run-down apartment building, sketch style, melancholic mood.",
    "Modern skyscraper with a reflective surface, abstract style, futuristic mood.",
    "Vintage storefronts on a cobblestone street, pastel style, quaint mood.",
    "Public transportation station with commuters, minimalist style, busy mood.",
    "Urban park with a fountain, oil painting style, tranquil mood.",
    "Industrial factory with smokestacks, mixed media style, ominous mood.",
    "Vintage camera with a leather strap, photorealistic style, classic mood.",
    "Antique typewriter with a stack of paper, sketch style, nostalgic mood.",
    "Colorful balloons floating in the sky, watercolor style, festive mood.",
    "Sparkling diamond necklace on a black background, minimalist style, luxurious mood.",
    "Retro radio with knobs and dials, mixed media style, vintage mood.",
    "Succulent plant in a ceramic pot, impressionist style, natural mood.",
    "Cup of steaming hot coffee on a saucer, oil painting style, cozy mood.",
    "Old-fashioned record player with vinyl records, pop art style, groovy mood.",
    "Glittering chandelier in a grand ballroom, photorealistic style, elegant mood.",
    "Colorful pinwheel spinning in the wind, cartoon style, playful mood.",
    "Antique book with gold-leaf pages, watercolor style, intellectual mood.",
    "Classic pocket watch on a chain, sketch style, timeless mood.",
    "Shiny red apple on a wooden table, pastel style, simple mood.",
    "Vintage telephone with a rotary dial, abstract style, nostalgic mood.",
    "Classic car with a polished chrome grille, mixed media style, retro mood.",
    "Majestic mountain range in the distance, oil painting style, serene mood.",
    "Bright yellow taxi on a busy city street, digital art style, chaotic mood.",
    "Majestic lion with a flowing mane, photorealistic style, powerful mood.",
    "Rustic wooden cabin in the woods, watercolor style, cozy mood.",
    "Vibrant street art on a brick wall, graffiti style, edgy mood.",
    "Whimsical hot air balloon floating in the clouds, mixed media style, dreamy mood.",
    "Traditional Japanese pagoda in a serene garden, ink drawing style, zen mood.",
    "Colorful butterfly in flight, impressionist style, whimsical mood.",
    "Spooky haunted mansion on a dark hill, dark art style, eerie mood.",
    "Elegant ballerina in a tutu, sketch style, graceful mood.",
    "Sparkling diamond ring on a velvet pillow, photorealistic style, luxurious mood.",
    "Romantic couple embracing in the rain, oil painting style, passionate mood.",
    "Modern skyscraper in a futuristic city, digital art style, high-tech mood.",
    "Scary jack-o-lantern on a porch, cartoon style, Halloween mood.",
    "Majestic bald eagle soaring through the sky, photorealistic style, majestic mood.",
    "Rustic windmill on a farm, watercolor style, peaceful mood.",
    "Vibrant cityscape at night, mixed media style, electric mood.",
    "Playful cartoon character eating a giant sandwich, pop art style, funny mood.",
    "Vintage travel poster for an exotic destination, impressionist style, adventurous mood.",
    "Regal peacock with colorful plumage, sketch style, proud mood.",
    "Modern abstract painting with bold colors, abstract style, creative mood.",
    "Mysterious abandoned carnival at night, dark art style, haunting mood.",
    "Colorful parrot perched on a branch, photorealistic style, tropical mood.",
    "Sleek sports car on an open road, oil painting style, adventurous mood.",
    "Beautiful mermaid swimming in the ocean, watercolor style, mystical mood.",
    "Intricate mandala design with vibrant colors, digital art style, spiritual mood.",
    "Cozy fireplace with crackling flames, mixed media style, warm mood.",
    "Whimsical unicorn prancing through a meadow, cartoon style, magical mood.",
    "Vintage movie poster for a classic film, photorealistic style, nostalgic mood.",
    "Elegant ballroom with a crystal chandelier, oil painting style, sophisticated mood.",
    "Cute cartoon animal playing a musical instrument, pop art style, fun mood.",
    "Beautiful waterfall in a lush forest, impressionist style, tranquil mood.",
    "Sleek motorcycle on an open road, watercolor style, daring mood.",
    "Futuristic spaceship soaring through the stars, digital art style, epic mood.",
    "Spooky graveyard at night with full moon, dark art style, ominous mood.",
    "Colorful rainbow over a peaceful countryside, mixed media style, hopeful mood.",
    "Whimsical fairy tale castle in the clouds, sketch style, fantastical mood.",
    "Classic still life painting of fruit, oil painting style, simple mood.",
    "Vibrant street scene in a bustling city, watercolor style, energetic mood.",
    "Cute cartoon character enjoying a bubble bath, pop art style, relaxing mood.",
    "Beautiful sailboat on a calm sea, photorealistic style, serene mood.",
    "Majestic tiger prowling through the jungle, oil painting style, fierce mood.",
    "Rustic barn on a country farm, watercolor style, peaceful mood.",
    "Iconic Eiffel Tower at sunset, realistic style, romantic mood.",
    "Famous Great Wall of China, watercolor style, historic mood.",
    "Enchanting Taj Mahal at sunrise, sketch style, serene mood.",
    "Grand Statue of Liberty, pastel style, patriotic mood.",
    "Futuristic cityscape, reflecting sunset, concept art",
    "Futuristic spaceship, landing on a red planet, 3D render",
    "Futuristic city, with flying cars and robots, digital painting",
    "Futuristic landscape, with glowing cities and mountains, matte painting",
    "Futuristic interior, with sleek furniture and holographic displays, vector design",
    "Ancient Egyptian temple, adorned with hieroglyphs, photorealistic",
    "Ancient Greek temple, surrounded by columns and statues, digital art",
    "Ancient Roman city, with ruins and crumbling buildings, 3D render",
    "Ancient forest, with towering trees and moss-covered rocks, matte painting",
    "Ancient cave, with stalactites and stalagmites, vector design",
    "Friendly robot, serving coffee, 3D render",
    "Friendly alien, waving hello, digital art",
    "Friendly dog, wagging its tail, 3D render",
    "Friendly cat, purring and rubbing against your leg, matte painting",
    "Friendly person, smiling and giving a thumbs up, vector design",
    "Surreal underwater garden, filled with glowing plants, digital painting",
    "Surreal landscape, with impossible architecture and floating islands, matte painting",
    "Surreal city, with buildings that twist and turn, vector design",
    "Surreal creature, with multiple eyes and limbs, 3D render",
    "Surreal object, with no apparent purpose or function, digital art",
    "Steampunk airship, soaring above forest, CGI",
    "Steampunk city, with cogs and gears everywhere, digital art",
    "Steampunk robot, with brass and leather armor, 3D render",
    "Steampunk weapon, with a steam-powered piston, matte painting",
    "Steampunk outfit, with a top hat and goggles, vector design",
    "Haunted Victorian mansion, shrouded in fog, gothic art",
    "Haunted house, with creaking doors and rattling windows, digital art",
    "Haunted forest, with glowing eyes in the darkness, 3D render",
    "Haunted graveyard, with tombstones and skeletons, matte painting",
    "Haunted object, that seems to move on its own, vector design",
    "Abstract geometric pattern, illuminated in neon colors, vector design",
    "Abstract painting, with swirling shapes and colors, digital art",
    "Abstract sculpture, with no apparent form or function, 3D render",
    "Abstract music, with no discernible melody or rhythm, matte painting",
    "Abstract poem, with no apparent meaning or structure, vector design",
    "Cyberpunk city street, bustling with neon signs, matte painting",
    "Cyberpunk nightclub, with flashing lights and loud music, digital art",
    "Cyberpunk hacker, breaking into a computer system, 3D render",
    "Cyberpunk vehicle, with sleek design and glowing lights, vector design",
    "Cyberpunk weapon, with a laser sight and a holographic sight, matte painting",
    "Majestic mountain range, basking in sunrise, landscape photography",
    "Majestic waterfall, crashing down a cliff face, digital art",
    "Majestic forest, with towering trees and lush green leaves, 3D render",
    "Majestic ocean, with waves crashing against the shore, matte painting",
    "Majestic animal, such as a lion or a tiger, vector design",
    "Whimsical unicorn, galloping through a field of flowers, digital art",
    "Whimsical teapot, with a spout that looks like a duck’s bill, 3D render",
    "Whimsical house, with a door that looks like a cat’s face, matte painting",
    "Whimsical creature, with a long tail and floppy ears, vector design",
    "Whimsical object, such as a toy or a piece of jewelry, digital art"
];